name: Generate Monkeytype Readme SVG

on:
  schedule:
    - cron: "0 */6 * * *"  # ogni 6 ore
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Monkeytype Readme SVG
        uses: monkeytype-hub/monkeytype-readme@v1.0.0
        with:
          username: ildesh
          themes: nord_light
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target-branch: monkeytype-readme
