name: Aggiorna Statistiche e Steam Card

on:
  schedule:
    - cron: "0 0 * * *" # Aggiorna a mezzanotte
  workflow_dispatch:

jobs:
  update-profile-cards:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Crea la cartella profile se non esiste
        run: mkdir -p profile

      - name: Scarica la Steam Card
        run: |
          curl -L "https://github-readme-steam-card.vercel.app/api/steamid/76561198355665966" -o profile/steam.svg
      
      - name: Genera l'immagine delle statistiche
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=ildesh&show_icons=true
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Salva le immagini nella repository
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add profile/
          git commit -m "Aggiornamento automatico Stats e Steam Card" || exit 0
          git push
